### ISSUE TITLE
"Errno::EBADF: Bad file descriptor" occasionally thrown by pollers and publishers

### ISSUE THREAD

**Issue by makeready** [wealthsimple/pheme#39]
E.g.
https://rollbar.com/wealthsimple/uk-brokerage/items/817/
https://rollbar.com/wealthsimple/uk-brokerage/items/784/

One-time poller error is not a big deal since it will retry, but publisher errors cause desynchronization of data between services.

Thanks!

**Comment by osman** [comment]
Did a bit of extra digging and this looks unrelated to pheme. Doing a search for `EBADF` or `Bad file descriptor` across all projects in rollbar shows that this is only happening to `uk-brokerage`. Moreover if you look farther back, things like Activerecord and jbuilder also present with the same error occasionally.

Looking for some of the other errors found, like

```
ActiveRecord::StatementInvalid: PG::ConnectionBad: PQconsumeInput() SSL SYSCALL error: Bad file descriptor
```

results in posts like [this](https://github.com/brianmario/mysql2/issues/547#issuecomment-64626667) and [this](https://stackoverflow.com/questions/19802233/heroku-sidekiq-activerecordstatementinvalid-pgunabletosend-ssl-syscall), which seems to point to an issue with setting the Rails database reaper to use too many threads.

for
```
Errno::EBADF: Bad file descriptor - rb_wait_for_single_fd()
```
[this](https://bitbucket.org/ged/ruby-pg/issues/282/bad-file-descriptor-rb_wait_for_single_fd) seems relevant and also points to postgres

**Comment by osman** [comment]
@makeready did we ever get to the bottom of this?

**Comment by osman** [comment]
@makeready any updates on this?

**Comment by makeready** [comment]
@osman Nope. We tried some experimental changes to sidekiq timers https://github.com/wealthsimple/skydome-playbooks/pull/3796

But it didn't seem to make these errors go away.

**Comment by cabello** [comment]
Did we rule out that pheme is not the problem here?

**Comment by osman** [comment]
closing as there is no action on this, please feel free to re-open as needed
